---
general:
  titel: TCI Generativ Art Generator 2 Lines Only
  describtion: Generiert mit Python
  date: 'yes'                                              # (yes / no) puts the creation date in the header
  autor: 'Thomas Cigolla'
  license: CC BY-NC 4.0
  make_png: 'yes'                                          # (yes / no)
  make_pdf: 'no'                                           # (yes / no)
  forground_colors: './assets/color_forground.yaml'
  background_colors: './assets/color_background.yaml'
note:
  show_palette: 'no'                  # (yes / no) Shows the used palette on the output file
grid:
  fields_x: 9
  fields_y: 12
  rectwidth: 200
  rectheight: 200
  background_color_fill: black               # none, color name (red) or hex
  # ################################################
line:
  number_lines: 800
  change_color: 'no'                # (yes / no)
  degree_min: 0
  degree_max: 15
  line_length_min: 200
  line_length_max: 400
  strok_width_min: 2
  strok_width_max: 8
stars:
  degree: 15
  number_stars: 30
  change_color: 'yes'             # (yes / no)
  line_length_min: 40
  line_length_max: 200
  strok_width_min: 2
  strok_width_max: 8
